import { LessonTemplate } from '@/components/lessons/LessonTemplate'
import type { ContentBlock } from '@/types/lesson'

const content: ContentBlock[] = [
  {id: '1', type: 'text', data: {content: `<h2>Composition et arrangement ✍️</h2><p>Créer ta propre musique est l\'aboutissement ultime de ton apprentissage. Tu deviens créateur, pas seulement interprète !</p>`, variant: 'normal'}},
  {id: '2', type: 'text', data: {content: `<h2>Les éléments de la composition</h2><p>Toute pièce musicale combine :</p><ul><li><strong>Mélodie</strong> : La ligne principale, mémorable</li><li><strong>Harmonie</strong> : Les accords qui soutiennent</li><li><strong>Rythme</strong> : Le pouls et la structure temporelle</li><li><strong>Texture</strong> : Combien de voix, quel style</li><li><strong>Forme</strong> : La structure globale (ABA, ABAB, etc.)</li></ul>`, variant: 'highlight'}},
  {id: '3', type: 'practice', data: {title: 'Exercice : Compose une mélodie simple', description: 'Première étape de création', steps: ['Choisis une tonalité (Do majeur pour commencer)', 'Invente une mélodie de 8 mesures', 'Utilise des notes de la gamme de Do majeur', 'Crée une phrase (4 mesures) et une réponse (4 mesures)', 'Termine sur la tonique (Do)', 'Note-la ou enregistre-la']}},
  {id: '4', type: 'text', data: {content: `<h2>Harmonisation d\'une mélodie</h2><p>Ajouter des accords à ta mélodie :</p><ul><li>Identifie les notes importantes (temps forts)</li><li>Choisis des accords qui contiennent ces notes</li><li>Utilise I, IV, V principalement</li><li>Ajoute des accords secondaires pour la couleur</li></ul>`, variant: 'normal'}},
  {id: '5', type: 'practice', data: {title: 'Exercice : Harmonise ta mélodie', description: 'Ajoute les accords', steps: ['Reprends ta mélodie de 8 mesures', 'Pour chaque mesure, choisis un accord', 'Commence et finis sur I (Do majeur)', 'Utilise IV et V pour créer du mouvement', 'Joue mélodie + accords', 'Ajuste si certains accords sonnent mal']}},
  {id: '6', type: 'text', data: {content: `<h2>Les formes musicales</h2><p>Structures courantes :</p><ul><li><strong>AB (binaire)</strong> : Deux sections contrastées</li><li><strong>ABA (ternaire)</strong> : Exposition, contraste, retour</li><li><strong>Rondo (ABACA)</strong> : Thème qui revient</li><li><strong>Thème et variations</strong> : Un thème, puis variations</li></ul>`, variant: 'tip'}},
  {id: '7', type: 'practice', data: {title: 'Exercice : Pièce en forme ABA', description: 'Structure complète', steps: ['Section A : ta mélodie de 8 mesures en Do majeur', 'Section B : 8 mesures dans une tonalité relative (La mineur)', 'Retour A : répète la section A', 'Tu as maintenant une pièce de 24 mesures !', 'Ajoute une introduction (4 mesures)', 'Ajoute une coda (fin, 4 mesures)']}},
  {id: '8', type: 'text', data: {content: `<h2>L\'arrangement : adapter une mélodie</h2><p>Arranger, c\'est transformer :</p><ul><li>Changer le style (classique → jazz)</li><li>Changer l\'instrumentation</li><li>Simplifier ou complexifier</li><li>Ajouter une introduction, un interlude, une coda</li></ul>`, variant: 'highlight'}},
  {id: '9', type: 'practice', data: {title: 'Exercice : Arrange "Joyeux anniversaire"', description: 'Transforme une mélodie connue', steps: ['Version 1 : Style classique avec accords simples', 'Version 2 : Style jazz avec accords de 7ème et 9ème', 'Version 3 : Style romantique avec arpèges', 'Version 4 : Style contemporain avec clusters', 'Compare les 4 versions', 'Laquelle préfères-tu ?']}},
  {id: '10', type: 'text', data: {content: `<h2>Techniques de développement</h2><p>Pour développer tes idées :</p><ul><li><strong>Transposition</strong> : Joue dans une autre tonalité</li><li><strong>Inversion</strong> : Retourne les intervalles</li><li><strong>Augmentation</strong> : Notes plus longues</li><li><strong>Diminution</strong> : Notes plus courtes</li><li><strong>Séquence</strong> : Répète en montant ou descendant</li></ul>`, variant: 'normal'}},
  {id: '11', type: 'practice', data: {title: 'Projet final : Compose une pièce complète', description: 'Ton opus 1', steps: ['Choisis un titre et un caractère (joyeux, mélancolique, etc.)', 'Compose le thème A (8 mesures)', 'Compose le thème B contrastant (8 mesures)', 'Crée une introduction (4 mesures)', 'Structure : Intro - A - B - A - Coda', 'Ajoute des nuances et de l\'expression', 'Note ta pièce ou enregistre-la', 'Félicitations : tu es compositeur !']}},
  {id: '12', type: 'text', data: {content: `<h2>Récapitulatif</h2><ul><li>✅ Créer une mélodie</li><li>✅ Harmoniser une mélodie</li><li>✅ Utiliser les formes musicales</li><li>✅ Arranger dans différents styles</li><li>✅ Composer une pièce complète</li></ul><p>La composition est un voyage sans fin. Continue à créer, à expérimenter, et ta voix musicale unique émergera !</p>`, variant: 'highlight'}}
]

export default function Lecon11Page() {
  return <LessonTemplate levelId={5} lessonNumber={11} title="Composition et arrangement" duration={26} objectives={['Composer une mélodie originale', 'Harmoniser une mélodie', 'Utiliser les formes musicales', 'Arranger dans différents styles', 'Créer une pièce complète']} content={content} previousLesson={{title: 'Improvisation et jazz', href: '/parcours/niveau-5/lecon-10'}} nextLesson={{title: 'Préparation concert et carrière', href: '/parcours/niveau-5/lecon-12'}} />
}
