import { LessonTemplate } from '@/components/lessons/LessonTemplate'
import type { ContentBlock } from '@/types/lesson'

const content: ContentBlock[] = [
  {id: '1', type: 'text', data: {content: `<h2>Préparation concert et carrière 🎭</h2><p>Félicitations ! Tu as parcouru les 5 niveaux et maîtrisé le piano. Cette dernière leçon te prépare à partager ton art avec le monde.</p>`, variant: 'normal'}},
  {id: '2', type: 'text', data: {content: `<h2>Préparer un récital</h2><p>Les étapes pour un concert réussi :</p><ul><li><strong>Choix du programme</strong> : 45-60 minutes, varié et équilibré</li><li><strong>Ordre des pièces</strong> : Commence fort, varie le rythme, finis spectaculairement</li><li><strong>Mémorisation</strong> : Connaître par cœur pour la liberté d\'expression</li><li><strong>Répétitions</strong> : Joue en situation plusieurs fois avant</li></ul>`, variant: 'highlight'}},
  {id: '3', type: 'practice', data: {title: 'Exercice : Construis ton programme', description: 'Crée un récital équilibré', steps: ['Pièce 1 : Baroque (Bach, 8 min)', 'Pièce 2 : Classique (Mozart, 10 min)', 'Entracte (5 min)', 'Pièce 3 : Romantique (Chopin, 12 min)', 'Pièce 4 : Contemporaine ou jazz (10 min)', 'Bis : Pièce courte et brillante', 'Total : ~45 minutes']}},
  {id: '4', type: 'text', data: {content: `<h2>Techniques de mémorisation</h2><p>Comment mémoriser solidement :</p><ul><li><strong>Mémorisation musicale</strong> : Structure, phrases, harmonies</li><li><strong>Mémorisation visuelle</strong> : "Vois" tes mains sur le clavier</li><li><strong>Mémorisation auditive</strong> : Chante mentalement</li><li><strong>Mémorisation kinesthésique</strong> : Mémoire musculaire</li></ul><p>Utilise les 4 types pour une mémorisation solide !</p>`, variant: 'normal'}},
  {id: '5', type: 'practice', data: {title: 'Exercice : Mémorisation en 4 étapes', description: 'Mémorise solidement', steps: ['Choisis 8 mesures d\'une pièce', 'Analyse l\'harmonie et la structure', 'Ferme les yeux, visualise tes mains', 'Chante la mélodie mentalement', 'Joue sans partition', 'Répète jusqu\'à automatisme complet']}},
  {id: '6', type: 'text', data: {content: `<h2>Gérer le trac</h2><p>Tout pianiste ressent du stress avant un concert :</p><ul><li><strong>Préparation</strong> : Connaître parfaitement son programme</li><li><strong>Respiration</strong> : Respire profondément avant d\'entrer</li><li><strong>Visualisation positive</strong> : Imagine un concert réussi</li><li><strong>Routine</strong> : Établis un rituel d\'avant-concert</li><li><strong>Acceptation</strong> : Un peu de stress améliore la performance</li></ul>`, variant: 'tip'}},
  {id: '7', type: 'practice', data: {title: 'Exercice : Simulation de concert', description: 'Pratique en situation', steps: ['Invite amis et famille', 'Habille-toi comme pour un concert', 'Annonce ton programme', 'Joue sans interruption', 'Salue et sors', 'Demande des retours constructifs', 'Recommence régulièrement']}},
  {id: '8', type: 'text', data: {content: `<h2>Carrières possibles</h2><p>Voies professionnelles pour pianistes :</p><ul><li><strong>Concertiste</strong> : Récitals et concerts</li><li><strong>Professeur</strong> : Enseigner dans école ou en privé</li><li><strong>Accompagnateur</strong> : Soutenir chanteurs et instrumentistes</li><li><strong>Pianiste de bar/restaurant</strong> : Ambiance musicale</li><li><strong>Compositeur/arrangeur</strong> : Créer de la musique</li><li><strong>Pianiste de studio</strong> : Enregistrements</li><li><strong>YouTubeur musical</strong> : Partager en ligne</li></ul>`, variant: 'highlight'}},
  {id: '9', type: 'text', data: {content: `<h2>Se construire une présence</h2><p>À l\'ère digitale :</p><ul><li><strong>Réseaux sociaux</strong> : Instagram, TikTok, YouTube</li><li><strong>Site web</strong> : Portfolio professionnel</li><li><strong>Enregistrements</strong> : Audio et vidéo de qualité</li><li><strong>Networking</strong> : Connecte avec d\'autres musiciens</li><li><strong>Concerts réguliers</strong> : Bâtis ton audience</li></ul>`, variant: 'normal'}},
  {id: '10', type: 'practice', data: {title: 'Exercice : Crée ton portfolio', description: 'Lance ta présence', steps: ['Enregistre 3 pièces (audio ou vidéo)', 'Crée une page Facebook/Instagram', 'Publie un enregistrement par semaine', 'Engage avec d\'autres musiciens en ligne', 'Cherche des opportunités de concert locales', 'Demande des témoignages à tes élèves/audience']}},
  {id: '11', type: 'text', data: {content: `<h2>L\'apprentissage continu</h2><p>Un virtuose ne cesse jamais d\'apprendre :</p><ul><li><strong>Masterclasses</strong> : Apprends de grands pianistes</li><li><strong>Concerts</strong> : Écoute des performances live</li><li><strong>Enregistrements</strong> : Étudie différentes interprétations</li><li><strong>Nouveau répertoire</strong> : Toujours explorer</li><li><strong>Autres styles</strong> : Jazz, pop, world music</li></ul><p>Le piano est un voyage sans fin !</p>`, variant: 'tip'}},
  {id: '12', type: 'text', data: {content: `<h2>Félicitations ! 🎉</h2><p>Tu as terminé le parcours complet des 5 niveaux de Pianely !</p><p>Tu es passé de débutant complet à pianiste accompli. Tu as les connaissances, la technique et la musicalité pour :</p><ul><li>✅ Jouer du répertoire classique, jazz et moderne</li><li>✅ Improviser et composer ta propre musique</li><li>✅ Donner des concerts</li><li>✅ Enseigner à d\'autres</li><li>✅ Continuer à progresser de façon autonome</li></ul><p><strong>Le piano est maintenant une part de toi.</strong></p><p>Continue à jouer, à explorer, à créer. La musique est un don que tu peux partager avec le monde entier.</p><p>Bravo, virtuose ! 🎹✨</p>`, variant: 'highlight'}}
]

export default function Lecon12Page() {
  return <LessonTemplate levelId={5} lessonNumber={12} title="Préparation concert et carrière" duration={28} objectives={['Préparer un récital complet', 'Maîtriser la mémorisation', 'Gérer le trac de scène', 'Explorer les carrières musicales', 'Construire une présence professionnelle']} content={content} previousLesson={{title: 'Composition et arrangement', href: '/parcours/niveau-5/lecon-11'}} />
}
