import { LessonTemplate } from '@/components/lessons/LessonTemplate'
import type { ContentBlock } from '@/types/lesson'

const content: ContentBlock[] = [
  {id: '1', type: 'text', data: {content: `<h2>Technique véloce : vitesse et précision ⚡</h2><p>La vélocité au piano combine vitesse, précision et musicalité. Dans cette leçon, nous allons explorer les techniques qui permettent de jouer rapidement sans sacrifier la clarté.</p>`, variant: 'normal'}},
  {id: '2', type: 'text', data: {content: `<h2>Les trilles</h2><p>Un <strong>trille</strong> est l'alternance rapide entre deux notes adjacentes. C'est un ornement essentiel du répertoire classique.</p><ul><li>Commence lentement et accélère progressivement</li><li>Utilise le mouvement du poignet, pas juste des doigts</li><li>Les doigts 2-3 ou 3-4 sont les plus courants</li></ul>`, variant: 'highlight'}},
  {id: '3', type: 'practice', data: {title: 'Exercice : Trilles', description: 'Développe la rapidité', steps: ['Main droite : Do-Ré alternance (doigts 2-3)', 'Commence à 60bpm : 4 notes par temps', 'Augmente à 80bpm, puis 100bpm', 'Garde les doigts arrondis et détendus', 'Pratique sur différentes paires de notes']}},
  {id: '4', type: 'text', data: {content: `<h2>Les ornements baroques</h2><p>Les <strong>ornements</strong> embellissent la mélodie. Les principaux sont :</p><ul><li><strong>Mordant</strong> : Note principale, note inférieure, note principale</li><li><strong>Gruppetto</strong> : Note supérieure, principale, inférieure, principale</li><li><strong>Appoggiature</strong> : Note d'ornement qui retarde la note principale</li></ul>`, variant: 'normal'}},
  {id: '5', type: 'practice', data: {title: 'Exercice : Mordant et gruppetto', description: 'Maîtrise les ornements', steps: ['Mordant sur Do : Do-Si-Do (rapide)', 'Gruppetto sur Do : Ré-Do-Si-Do', 'Applique à une mélodie simple', 'Écoute des pièces baroques pour le style']}},
  {id: '6', type: 'text', data: {content: `<h2>Les gammes rapides</h2><p>Pour jouer des gammes à grande vitesse :</p><ul><li>Rotation du poignet lors du passage du pouce</li><li>Mouvement circulaire fluide</li><li>Détente totale entre chaque passage</li><li>Utilise le poids du bras, pas la force des doigts</li></ul>`, variant: 'tip'}},
  {id: '7', type: 'practice', data: {title: 'Exercice : Gamme rapide', description: 'Augmente la vitesse progressivement', steps: ['Do majeur main droite à 120bpm', 'Focalis sur le passage du pouce fluide', 'Augmente à 140bpm, 160bpm, 180bpm', 'Ne sacrifie jamais la clarté pour la vitesse']}},
  {id: '8', type: 'text', data: {content: `<h2>Les glissandos</h2><p>Un <strong>glissando</strong> est un glissement rapide sur le clavier. Spectaculaire et expressif !</p><ul><li>Utilise le dos de l'ongle (glissando ascendant)</li><li>Utilise la pulpe du pouce (glissando descendant)</li><li>Garde le poignet souple</li></ul>`, variant: 'normal'}},
  {id: '9', type: 'practice', data: {title: 'Exercice : Glissando', description: 'Technique d\'effet', steps: ['Glissando ascendant sur touches blanches', 'Main droite, dos des ongles des doigts 2-3-4', 'Mouvement rapide et fluide', 'Glissando descendant avec le pouce', 'Pratique jusqu\'à obtenir un son lisse']}},
  {id: '10', type: 'text', data: {content: `<h2>Les octaves rapides</h2><p>Jouer des octaves à grande vitesse demande :</p><ul><li>Rotation du poignet</li><li>Mouvement de "rebond"</li><li>Force venant de l'avant-bras, pas des doigts</li><li>Détente immédiate après chaque octave</li></ul>`, variant: 'highlight'}},
  {id: '11', type: 'practice', data: {title: 'Exercice : Octaves véloces', description: 'Développe la puissance et la vitesse', steps: ['Gamme en octaves main droite lentement', 'Focus sur le rebond du poignet', 'Augmente progressivement le tempo', 'Pratique seulement 5 minutes (très exigeant)']}},
  {id: '12', type: 'text', data: {content: `<h2>Programme d\'entraînement quotidien</h2><ul><li>5 min : Trilles sur toutes les notes</li><li>5 min : Gammes rapides avec métronome</li><li>5 min : Passages difficiles lents puis rapides</li><li>5 min : Repos et étirements</li></ul><p>La vitesse vient avec le temps, la patience et la régularité !</p>`, variant: 'tip'}},
  {id: '13', type: 'text', data: {content: `<h2>Récapitulatif</h2><ul><li>✅ Les trilles et leur technique</li><li>✅ Les ornements baroques</li><li>✅ Les gammes à grande vitesse</li><li>✅ Les glissandos</li><li>✅ Les octaves véloces</li></ul>`, variant: 'highlight'}}
]

export default function Lecon5Page() {
  return <LessonTemplate levelId={5} lessonNumber={5} title="Technique véloce" duration={21} objectives={['Maîtriser les trilles', 'Exécuter les ornements baroques', 'Jouer des gammes rapides avec fluidité', 'Réaliser des glissandos', 'Développer les octaves véloces']} content={content} previousLesson={{title: 'Rythmes avancés et polyrythmies', href: '/parcours/niveau-5/lecon-4'}} nextLesson={{title: 'Pédales avancées', href: '/parcours/niveau-5/lecon-6'}} />
}
